require File.join(File.dirname(__FILE__), 'config', 'boot')

import File.join(RADIANT_ROOT, 'Rakefile')

begin
  require 'cucumber/rake/task'

  Cucumber::Rake::Task.new(:metry_features) do |t|
    t.fork = true
    t.cucumber_opts = ['--format', (ENV['CUCUMBER_FORMAT'] || 'pretty')]
  end
  task :metry_features => ['cucumber', 'db:test:prepare']
  task :cucumber do
    ENV["RAILS_ENV"] = "cucumber"
  end
rescue LoadError
  desc 'Cucumber rake task not available'
  task :metry_features do
    abort 'Cucumber rake task is not available. Be sure to install cucumber as a gem or plugin'
  end
end
